insert into Courses (Name, Price) values (N'CourseName1', 1000);
insert into Courses (Name, Price) values (N'CourseName2', 1000);
insert into Courses (Name, Price) values (N'CourseName3', 1000);
insert into Courses (Name, Price) values (N'CourseName4', 1000);
insert into Courses (Name, Price) values (N'CourseName5', 1000);
insert into Courses (Name, Price) values (N'CourseName6', 1000);
insert into Courses (Name, Price) values (N'CourseName7', 1000);
insert into Courses (Name, Price) values (N'CourseName8', 1000);
insert into Courses (Name, Price) values (N'CourseName9', 1000);
insert into Courses (Name, Price) values (N'CourseName10', 1000);
insert into Courses (Name, Price) values (N'CourseName11', 1000);
insert into Courses (Name, Price) values (N'CourseName12', 1000);
insert into Courses (Name, Price) values (N'CourseName13', 1000);
insert into Courses (Name, Price) values (N'CourseName14', 1000);
insert into Courses (Name, Price) values (N'CourseName15', 1000);
insert into Courses (Name, Price) values (N'CourseName16', 1000);
insert into Courses (Name, Price) values (N'CourseName17', 1000);
insert into Courses (Name, Price) values (N'CourseName18', 1000);
insert into Courses (Name, Price) values (N'CourseName19', 1000);
insert into Courses (Name, Price) values (N'CourseName20', 1000);
insert into Courses (Name, Price) values (N'CourseName21', 1000);
insert into Courses (Name, Price) values (N'CourseName22', 1000);
insert into Courses (Name, Price) values (N'CourseName23', 1000);
insert into Courses (Name, Price) values (N'CourseName24', 1000);

insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 1', N'Длинное описание курса 1', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 2', N'Длинное описание курса 2', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 3', N'Длинное описание курса 3', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 4', N'Длинное описание курса 4', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 5', N'Длинное описание курса 5', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 6', N'Длинное описание курса 6', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 7', N'Длинное описание курса 7', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 8', N'Длинное описание курса 8', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 9', N'Длинное описание курса 9', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 10', N'Длинное описание курса 10', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 11', N'Длинное описание курса 11', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 12', N'Длинное описание курса 12', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 13', N'Длинное описание курса 13', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 14', N'Длинное описание курса 14', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 15', N'Длинное описание курса 15', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 16', N'Длинное описание курса 16', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 17', N'Длинное описание курса 17', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 18', N'Длинное описание курса 18 ', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 19', N'Длинное описание курса 19', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 20', N'Длинное описание курса 20', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 21', N'Длинное описание курса 21', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 22', N'Длинное описание курса 22', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 23', N'Длинное описание курса 23', 1000);
insert into CourseDescription (ShortDescription, LongDescription, CourseLength) values (N'Короткое описание курса 24', N'Длинное описание курса 24', 1000);
