//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edu.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
    
        public virtual CourseDescriptions CourseDescriptions { get; set; }
    }
}
